# Generated by Django 5.1.6 on 2025-04-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'HARD')], default='Easy', max_length=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Gluten Free', 'Gluten Free')], default='Healthy', max_length=11),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_to_cook',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
