# Generated by Django 5.1.6 on 2025-04-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_difficulty_recipe_tag_recipe_time_to_cook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_to_cook',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
