# Generated by Django 5.1.6 on 2025-04-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_time_to_cook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.CharField(blank=True, choices=[('Healthy', 'Healthy'), ('Gluten Free', 'Gluten Free')], max_length=11, null=True),
        ),
    ]
